### ISSUE TITLE
Implement extract_examples()

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/testr#8]
We need a reliable `extract_examples` method which extracts all examples from a given package that are _not_ marked with `/dontrun` or `/donttest`.

It should look like this:

```
> extract_examples("stats")
[1] "-log(dpois(0:7, lambda = 1) * gamma(1+ 0:7)) # ==\nNi <- rpois(50, lambda = 4); table(factor(Ni, 0:max(Ni)))"
[2] "x <- -1:(4*6 + 1)\nx <- -1:(4*6 + 1)"
..etc
```

**Comment by akbertram** [comment]
@psolaimani let me know if this is already implemented somewhere in testr.

**Comment by psolaimani** [comment]
@akbertram there is no such function yet. I have adjusted the previous function to handle `Not run` codes in examples. It should work now, trying it out at the moment.

so now all the code we need to use is: `R -e 'library(testr); generate_test_cases()'`
